{% set name = "blis" %}
{% set version = "1.3.0" %}

package:
  name: cython-{{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1695a87e3fc4c20d9b9140f5238cac0514c411b750e8cdcec5d8320c71f62e99

build:
  number: 0
  missing_dso_whitelist:  # [linux]
    - $RPATH/ld64.so.1    # [linux]
  skip: True  # [py<36 or py>313]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - pip
    - python
    - wheel
    - setuptools
    - cython >=3.0,<4.0
    - numpy >=1.19.3,<3.0.0
  run:
    - python
    - numpy >=1.15.0,<3.0.0  # [py<39]
    - numpy >=1.19.0,<3.0.0  # [py>=39]

test:
  imports:
    - blis
    - blis.py
    - blis.cy
  commands:
    - pip check
    - pytest --tb=native --pyargs blis
  requires:
    - pip
    - pytest
    - hypothesis

about:
  home: https://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: 'Fast matrix-multiplication as a self-contained Python library - no system dependencies!'
  description: |
    cython-blis provides the Blis linear algebra routines as a self-contained Python C-extension.
  doc_url: https://github.com/explosion/cython-blis/blob/master/README.md
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
  skip-lints:
    - should_use_stdlib
