{% set version = "0.7.6" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blis/blis-{{ version }}.tar.gz
  sha256: fe97b10f68a1c7b54c0e54beada84e18f4efb68dd40c906fb8748f5114743ec6

build:
  number: 1
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - cython
    - python
    - pip
    - python
    - setuptools
    - numpy >=1.16
    - wheel
  run:
    - python
    - numpy >=1.16

test:
  imports:
    - blis
    - blis.py
    - blis.cy

about:
  home: http://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: 'Fast matrix-multiplication as a self-contained Python library – no system dependencies!'

  doc_url: https://github.com/explosion/cython-blis
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
