{% set version = "1.0.1" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blis/blis-{{ version }}.tar.gz
  sha256: 91739cd850ca8100dcddbd8ad66942cab20c9473cdea9a35b165b11d7b8d91e4

build:
  number: 0
  # numpy-base >=2.0.0 requires python >=3.9
  skip: True  # [py<39]
  missing_dso_whitelist:  # [linux and s390x]
    - $RPATH/ld64.so.1    # [linux and s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - python
    - cython 0.29
    - numpy >=2.0.0,<2.1.0
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=2.0.0,<2.1.0

test:
  imports:
    - blis
    - blis.py
    - blis.cy
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - pytest --tb=native --pyargs blis

about:
  home: https://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: 'Fast matrix-multiplication as a self-contained Python library - no system dependencies!'
  description: |
    cython-blis provides the Blis linear algebra routines as a self-contained Python C-extension.
  doc_url: https://github.com/explosion/cython-blis/blob/master/README.md
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
