{% set version = "0.7.11" %}

package:
  name: cython-blis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blis/blis-{{ version }}.tar.gz
  sha256: cec6d48f75f7ac328ae1b6fbb372dde8c8a57c89559172277f66e01ff08d4d42

build:
  number: 0
  missing_dso_whitelist:  # [linux and s390x]
    - $RPATH/ld64.so.1    # [linux and s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev  # [win]
  host:
    - python
    - cython 0.29
    - numpy  {{ numpy }}
    - pip
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - blis
    - blis.py
    - blis.cy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/explosion/cython-blis
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - blis/LICENSE
  summary: 'Fast matrix-multiplication as a self-contained Python library – no system dependencies!'
  description: |
    cython-blis provides the Blis linear algebra routines as a self-contained Python C-extension.
  doc_url: https://github.com/explosion/cython-blis/blob/master/README.md
  dev_url: https://github.com/explosion/cython-blis

extra:
  recipe-maintainers:
    - honnibal
    - ines
